const regions = {
    ARGENTINA: "Argentina",
    AUSTRALIA: "Australia",
    BELGIUM: "Belgium",
    BOLIVIA: "Bolivia",
    BOSNIA_AND_HERZEGOVINA: "Bosnia and Herzegovina",
    CANADA: "Canada",
    DENMARK: "Denmark",
    ENGLAND: "England",
    FRANCE: "France",
    GERMANY: "Germany",
    GREECE: "Greece",
    INDIA: "India",
    ITALY: "Italy",
    JAPAN: "Japan",
    NETHERLANDS: "Netherlands",
    NORTHERN_IRELAND: "Northern Ireland",
    QUEBEC: "Québec",
    SCOTLAND: "Scotland",
    SOUTH_AFRICA: "South Africa",
    SPAIN: "Spain",
    SWEDEN: "Sweden",
    SWITZERLAND: "Switzerland",
    USA: "USA", // TODO split by region
    WALES: "Wales",
}